# -*- coding: utf-8 -*-
"""src/build_finbert_embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJSeGGjYus1kN1HDtFIbY78eThrrCfx8
"""

#!/usr/bin/env python3
"""
src/build_finbert_embeddings.py

Compute FinBERT sentence embeddings for headlines/text and write:
    data/processed/text_embeddings_finbert.parquet
Output schema: columns ['date' (normalized midnight), 'text_emb' (python list), 'text_raw' (optional)]

Usage example:
    python src/build_finbert_embeddings.py \
      --news_csv data/raw/RedditNews.csv \
      --out data/processed/text_embeddings_finbert.parquet \
      --text_col News --date_col Date --device cpu --batch_size 64
"""
import argparse
from pathlib import Path
from typing import List
import pandas as pd
import numpy as np
import torch
from transformers import AutoTokenizer, AutoModel
from tqdm import tqdm

def mean_pool(token_embeddings, attention_mask):
    # token_embeddings: (batch, seq_len, dim)
    mask = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    summed = torch.sum(token_embeddings * mask, dim=1)
    counts = torch.clamp(mask.sum(dim=1), min=1e-9)
    return (summed / counts)

def compute_embeddings(texts: List[str], model, tokenizer, device, batch_size=64):
    model.to(device)
    embeddings = []
    for i in tqdm(range(0, len(texts), batch_size), desc="FinBERT embed"):
        batch = texts[i:i+batch_size]
        enc = tokenizer(batch, padding=True, truncation=True, return_tensors="pt", max_length=256)
        input_ids = enc["input_ids"].to(device)
        attn = enc["attention_mask"].to(device)
        with torch.no_grad():
            out = model(input_ids=input_ids, attention_mask=attn, return_dict=True)
            last_hidden = out.last_hidden_state  # (batch, seq_len, dim)
            pooled = mean_pool(last_hidden, attn) # (batch, dim)
            arr = pooled.cpu().numpy()
        embeddings.append(arr)
    embeddings = np.vstack(embeddings)
    return embeddings

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--news_csv", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--text_col", default=None)
    p.add_argument("--date_col", default=None)
    p.add_argument("--model_name", default="yiyanghkust/finbert-tone", help="FinBERT variant")
    p.add_argument("--device", default="cpu")
    p.add_argument("--batch_size", type=int, default=64)
    args = p.parse_args()

    df = pd.read_csv(args.news_csv)
    if args.text_col is None:
        # try common columns
        for c in ("title","headline","news","text","News"):
            if c in df.columns:
                args.text_col = c; break
    if args.text_col is None:
        raise ValueError("Provide --text_col pointing to text (title/headline).")

    if args.date_col is None:
        for c in ("date","Date","timestamp","time"):
            if c in df.columns:
                args.date_col = c; break

    # prepare text series
    texts = df[args.text_col].fillna("").astype(str).tolist()
    if args.date_col is not None:
        dates = pd.to_datetime(df[args.date_col], errors="coerce").dt.normalize().tolist()
    else:
        dates = [pd.NaT]*len(texts)

    print("Loading FinBERT:", args.model_name)
    tokenizer = AutoTokenizer.from_pretrained(args.model_name, use_fast=True)
    model = AutoModel.from_pretrained(args.model_name)
    device = torch.device(args.device if torch.cuda.is_available() and args.device!="cpu" else "cpu")

    embs = compute_embeddings(texts, model, tokenizer, device, batch_size=args.batch_size)
    out_df = pd.DataFrame({"date": dates, "text_emb": [e.tolist() for e in embs], "text_raw": texts})
    out_df.to_parquet(args.out, index=False)
    print("Wrote FinBERT embeddings to", args.out)

if __name__ == "__main__":
    main()