# -*- coding: utf-8 -*-
"""event_tagging_and_conditional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJSeGGjYus1kN1HDtFIbY78eThrrCfx8
"""

#!/usr/bin/env python3
"""
src/event_tagging_and_conditional.py

1) Read existing text_embeddings parquet (or CSV with text),
2) Tag each row into event types via keywords (macro / firm / geopolitical / other).
3) (Optional) Train a TF-IDF classifier to label more data if you have human-labeled subset.
4) Output a parquet with event_type that can be merged/used by training script.

Usage:
    python src/event_tagging_and_conditional.py \
      --text_emb data/processed/text_embeddings.parquet \
      --out data/processed/text_embeddings_event.parquet
"""
import argparse
from pathlib import Path
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# lightweight keyword maps (extend for your dataset)
EVENT_KEYWORDS = {
    "macro": ["fed", "rate", "inflation", "gdp", "unemployment", "cpi", "economy", "interest rate", "central bank"],
    "firm" : ["earnings", "ipo", "merger", "acquisition", "announces", "quarter", "guidance", "revenue", "profit", "layoff"],
    "geo"  : ["war", "sanction", "geopolitical", "attack", "conflict", "election", "policy", "diplomatic", "embargo"]
}

def rule_tag(text: str):
    if not isinstance(text, str): return "other"
    t = text.lower()
    for k, kws in EVENT_KEYWORDS.items():
        for kw in kws:
            if kw in t:
                return k
    return "other"

def build_conditional_features(df_text: pd.DataFrame):
    # df_text must have columns: date, text_raw, text_emb
    df = df_text.copy()
    if "text_raw" not in df.columns:
        # fallback: reconstruct from e.g. stored 'title' or drop to 'other'
        df["text_raw"] = df.get("title", "").fillna("").astype(str)
    df["event_type"] = df["text_raw"].apply(rule_tag)
    # one-hot event types
    dummies = pd.get_dummies(df["event_type"], prefix="evt")
    # create embedding interaction features (example: mean of emb × event indicator)
    emb_arr = np.vstack(df["text_emb"].apply(lambda x: np.array(x, dtype=float)).values)
    emb_mean = emb_arr.mean(axis=1)  # quick summary scalar per row
    df["emb_mean"] = emb_mean
    # create event × emb_mean interactions
    for col in dummies.columns:
        df[f"{col}_x_embmean"] = dummies[col].astype(float) * df["emb_mean"]
    # keep smaller set: date, text_emb, event_type, emb_mean, dummies, interactions
    keep = ["date","text_emb","text_raw","event_type","emb_mean"] + dummies.columns.tolist() + [c for c in df.columns if c.endswith("_x_embmean")]
    out = df[keep].copy()
    return out

def optional_train_event_classifier(df_text: pd.DataFrame, labeled_df: pd.DataFrame=None):
    # If you have a small labeled dataset (date + text + event_type) pass labeled_df to train a TF-IDF classifier.
    # This function returns a trained classifier and vectorizer.
    if labeled_df is None:
        return None, None
    tf = TfidfVectorizer(max_features=5000, ngram_range=(1,2))
    X = tf.fit_transform(labeled_df["text_raw"].astype(str).tolist())
    y = labeled_df["event_type"].astype(str).tolist()
    clf = LogisticRegression(max_iter=1000)
    clf.fit(X, y)
    return clf, tf

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--text_emb", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--labeled_csv", default=None, help="Optional small labeled CSV with columns text_raw,event_type")
    args = p.parse_args()

    df = pd.read_parquet(args.text_emb)
    # ensure text_raw exists or try title/body
    if "text_raw" not in df.columns:
        if "title" in df.columns:
            df["text_raw"] = df["title"].astype(str).fillna("")
        else:
            df["text_raw"] = [""] * len(df)

    df_tagged = build_conditional_features(df)

    # optional classifier training if labeled file provided
    if args.labeled_csv:
        labeled = pd.read_csv(args.labeled_csv)
        clf, tf = optional_train_event_classifier(df, labeled)
        if clf is not None:
            # predict on full set and override where classifier is confident
            X_all = tf.transform(df_tagged["text_raw"].astype(str).tolist())
            preds = clf.predict(X_all)
            df_tagged["event_type"] = preds

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    df_tagged.to_parquet(args.out, index=False)
    print("Wrote tagged embeddings to", args.out)
    print("Event type counts:\n", df_tagged["event_type"].value_counts())

if __name__ == "__main__":
    main()